-- Auto-generated by GMToolBox — overwritten on character entitlement sync.
-- Stub so GmShared.toc always loads a table before EntitlementGate.lua.
GmtEntitlements = GmtEntitlements or {}
GmtEntitlements.hasCore = true
GmtEntitlements.valid = true
GmtEntitlements.characterGuid = ""
GmtEntitlements.characterName = ""
GmtEntitlements.coreExpiresUtc = ""
GmtEntitlements.maxInstances = 64
GmtEntitlements.addons = {}
GmtEntitlements.allowedNames = {}
GmtEntitlements.updatedUtc = ""
